# @package _global_
dataset:
  _target_: src.data.SyntheticPkpdDatasetCollection     # Will be dynamically instantiated
  name: pkpd_generator
  equation_str: ???
  coeff: ???                                            # Confounding coefficient (gamma)
  conf_coeff: ${dataset.coeff}                          # Confounding coefficient 
  seed: ${exp.seed}
  num_patients:
    train: ???
    val: ???
    test: ???
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  max_seq_length: 60                                    # Max length of time series
  projection_horizon: 5                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  cf_seq_mode: sliding_treatment                        # sliding_treatment / random_trajectories
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multiclass                            # multiclass / multilabel -- for RMSN

model:
  dim_treatments: 2
  dim_vitals: 0
  dim_static_features: 2
  dim_outcomes: 1

exp:
  unscale_rmse: True
  percentage_rmse: True
